# Generated by Django 3.1.3 on 2020-11-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dietician', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='Date',
        ),
    ]
