# Generated by Django 3.1.3 on 2020-11-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dietician', '0002_auto_20201122_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Date',
            new_name='date',
        ),
    ]
