# Generated by Django 3.1.3 on 2020-11-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dietician', '0003_auto_20201122_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='Date',
        ),
    ]
