# Generated by Django 3.1.3 on 2020-11-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet_calculations', '0015_remove_calculations_exerciselvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculations',
            name='Exerciselvl',
            field=models.IntegerField(default=1),
        ),
    ]
