# Generated by Django 3.1.3 on 2020-11-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dish_Recomendation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
